server:
  port: 8080
spring:
  application:
    name: ifox-admin
  profiles:
    active: dev
springdoc:
  swagger-ui:
    docExpansion: list
    displayRequestDuration: true
    showExtensions: true
    showCommonExtensions: true
    defaultModelsExpandDepth: -1
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
    resolve-schema-properties: true
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: ifox-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: ifox
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时

secure:
  ignored:
    urls: #安全路径白名单
      - /
      - /static/**
      - /swagger-ui.html
      - /swagger-ui/**
      - /v3/api-docs/**
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
