server:
  port: 8080
spring:
  application:
    name: ifox-admin
  flyway:
    locations: classpath:/db/migration/
    baseline-on-migrate: true
  profiles:
    active: dev
springdoc:
  swagger-ui:
    docExpansion: list
    displayRequestDuration: true
    showExtensions: true
    showCommonExtensions: true
    defaultModelsExpandDepth: -1
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
    resolve-schema-properties: true
security:
  jwt:
    secret: KGCwJRfTBS3WUOJeolmdFZ3nqEpyC0zGYlym1WAFTFTU67YHP5flv+00ivTYbfCvtBdcWDa+Xw1isuRCLlmn0w==
    tokenHeader: Authorization #JWT存储的请求头
    expiration: 604800 #JWT的超期限时间(60*60*24*7)
    tokenHead: 'Bearer '  #JWT负载中拿到开头
    issuer: ${spring.application.name:ifox}
  ignored:
    urls: #安全路径白名单
      - /
      - /static/**
      - /swagger-ui.html
      - /swagger-ui/**
      - /v3/api-docs/**
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /actuator/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
