spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ifox_admin?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      pool-name: ${spring.application.name}
      connection-test-query: select 1 from dual
      validation-timeout: 10000
      read-only: false
      minimum-idle: 5
      maximum-pool-size: 15
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1200000
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    timeout: 3000ms
logging:
  level:
    root: info
    com.ifoxhub.admin: debug
management:
  health:
    redis:
      enabled: false
ifox:
  cache:
    server: caffeine